/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'stars': MotiaStream<{ id: string; stars: number; name: string; fullName: string; owner: string; description: string | unknown; language: string | unknown; lastUpdated: string; history?: Array<{ date: string; stars: number }> }>
    'repoUpdates': MotiaStream<{ id: string; owner: string; repo: string; type: 'commit' | 'push' | 'branch' | 'refresh'; message: string; author?: string; sha?: string; timestamp: string; nodeCount?: number; linkCount?: number }>
  }

  interface Handlers {
    'WatchRepo': ApiRouteHandler<{ owner: string; repo: string; token?: string }, ApiResponse<200, { success: boolean; message: string; watchId: string }> | ApiResponse<500, { error: string }>, never>
    'TrackStars': ApiRouteHandler<{ owner: string; repo: string; token?: string }, ApiResponse<200, { success: boolean; stars: number; name: string; fullName: string }> | ApiResponse<500, { error: string }>, { topic: 'fetch-star-history'; data: { owner: string; repo: string; token?: string } }>
    'GetStarHistory': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { owner: string; repo: string; totalStars: number; history: Array<{ date: string; stars: number }> }> | ApiResponse<403, { error: string }> | ApiResponse<500, { error: string }>, never>
    'GetRepoTree': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { nodes: Array<{ id: string; name: string; type: 'blob' | 'tree'; path: string; size?: number; extension?: string; parentId?: string | unknown; fx?: number; fy?: number }>; links: Array<{ source: string; target: string }> }> | ApiResponse<403, { error: string }> | ApiResponse<500, { error: string }>, never>
    'Get Repository Details': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'FetchStarHistoryEvent': EventHandler<{ owner: string; repo: string; token?: string }, never>
    'EmbedStarHistory': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'EmbedStarBadge': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}